name: Branch Name

on:
  pull_request:
    branches:
      - master
    types: [opened, edited, reopened, synchronize]
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: npm ci --no-audit --prefer-offline
      - name: Verify Branch Name
        uses: ./.github/actions/branch-name
        with:
          branch-name: "${{ github.head_ref }}"
