name: Pull Request Name

on:
  pull_request:
    branches:
      - master
    types: [opened, edited, reopened, synchronize]
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: npm ci
      - name: Verify Pull Request Name
        uses: ./.github/actions/pull-request-name
